defmodule Imgur.Model.GalleryImage do
  defstruct [
    :id,
    :title,
    :description,
    :datetime,
    :type,
    :animated,
    :width,
    :height,
    :size,
    :views,
    :bandwidth,
    :deletehash,
    :link,
    :gifv,
    :mp4,
    :mp4_size,
    :looping,
    :vote,
    :favorite,
    :nsfw,
    :comment_count,
    :topic,
    :topic_id,
    :section,
    :account_url,
    :account_id,
    :ups,
    :downs,
    :points,
    :score,
    :is_album,
    :in_most_viral
  ]
  @type t :: %Imgur.Model.GalleryImage{
    id: String.t,
    title: String.t,
    description: String.t,
    datetime: integer,
    type: String.t,
    animated: boolean,
    width: integer,
    height: integer,
    size: integer,
    views: integer,
    bandwidth: integer,
    deletehash: String.t,
    link: String.t,
    gifv: String.t,
    mp4: String.t,
    mp4_size: integer,
    looping: boolean,
    vote: String.t,
    favorite: boolean,
    nsfw: boolean,
    comment_count: integer,
    topic: String.t,
    topic_id: integer,
    section: String.t,
    account_url: String.t,
    account_id: integer,
    ups: integer,
    downs: integer,
    points: integer,
    score: integer,
    is_album: boolean,
    in_most_viral: boolean
  }

  @spec schema() :: Imgur.Model.GalleryImage.t
  def schema(), do: %Imgur.Model.GalleryImage{}
end
